

export default [
    {
        id: 0,
        img: "/Wet-n-Wild-Silk-Finish-Lipstick-527B-Fuchsia-w-Blue-Pearl_ccf51cff-56ae-4a1d-b74b-67fa38aa1d57.6c45f7c50242e6efed98d9f9df3c733b.jpeg",
        name: "Wild Silk Finish Lipstick",
        price: 41.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 1,
        img: "/Pink-Sugar-Creamy-Matte-Lipstick-Bangbang.jpg",
        name: "Creamy Matte Lipstick",
        price: 46.0,
        category: ["lipsticks"],
        sale: true,
    },
    {
        id: 2,
        img: "/15662584202-4-700.jpg",
        name: "Sensuously Matte Lipstick",
        price: 41.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 3,
        img: "/OIP (13).jpeg",
        name: "Palladio Beauty Matte Blush",
        price: 26.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 4,
        img: "/R (2).jpeg",
        name: "Olay Quench Ultra Moisture Body Lotion",
        price: 32.0,
        category: ["skin care"],
        sale: true,
    },
    {
        id: 5,
        img: "/R (1).jpeg",
        name: "Himalaya Moisturizing Aloe Vera Face Wash",
        price: 30.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 6,
        img: "/79.jpg",
        name: "Selin Beauty Be Natural",
        price: 44.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 7,
        img: "/R.png",
        name: "Laikou Makeup Professional Liquid Foundation",
        price: 55.0,
        category: ["makeup"],
        sale: true,
    },
    {
        id: 8,
        img: "/2efc52a0-03e4-0134-e751-0a315da82319.avif",
        name: "Eyebrow Kit",
        price: 35.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 9,
        img: "/OIP (12).jpeg",
        name: "NYX Jumbo Eye Pencil",
        price: 36.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 10,
        img: "/R.jpeg",
        name: "Maybelline Liquid Eyeliner",
        price: 51.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 11,
        img: "/OIP (11).jpeg",
        name: "Maybelline Hypercurl Waterproof Mascara",
        price: 51.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 12,
        img: "/10271186.jpeg",
        name: "Salicylic Acid Cleanser",
        price: 34.0,
        category: ["skin care"],
        sale: true,
    },
    {
        id: 13,
        img: "/11624258830366.jpg",
        name: "Sally Hansen Xtreme Wear Nail Polish Black",
        price: 20.0,
        category: ["lipsticks", "nail & wax"],
        sale: false,
    },
    {
        id: 14,
        img: "/OIP (10).jpeg",
        name: "Sally Hansen Xtreme Wear Nail Polish Pink Punk",
        price: 20.0,
        category: ["lipsticks", "nail & wax"],
        sale: true,
    },
    {
        id: 15,
        img: "/369620.webp",
        name: "Sally Hansen Xtreme Wear Nail Polish Cherry Red",
        price: 20.0,
        category: ["makeup", "nail & wax"],
        sale: false,
    },
    {
        id: 16,
        img: "/OIP (9).jpeg",
        name: "Iconic London Lip Plumping Gloss Sweet Talk",
        price: 37.0,
        category: ["lipsticks"],
        sale: true,
    },
    {
        id: 17,
        img: "/imgonline-com-ua-resize-5diCyA2ewnQidP90_large.webp",
        name: "OH MY GLAM",
        price: 21.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 18,
        img: "/f3a0fe52-6c66-4a7c-bf1b-07b5f2518336_1.921d2d0c9008943b5cf04a612ba1ab5c.webp",
        name: "Hard Candy Plumping Serum Lip Gloss",
        price: 36.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 19,
        img: "/B0047183.png",
        name: "GLAM Glitter Liquid Eyeshadow",
        price: 27.0,
        category: ["makeup"],
        sale: false,
    },
    {
        id: 20,
        img: "/690502-07__63965.jpg",
        name: "NYX Velvet Matte Lipstick",
        price: 25.0,
        category: ["lipsticks", "makeup"],
        sale: true,
    },
    {
        id: 21,
        img: "/OIP (8).jpeg",
        name: "Olay Serums",
        price: 36.0,
        category: ["skin care"],
        sale: true,
    },
    {
        id: 22,
        img: "/123b5fb5-73ff-4b8d-b5e9-e455a0fea659_1.82eacbd62ac67e143a23ff18c2526d06.webp",
        name: "Hansen Vitamins C Cleanser",
        price: 33.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 23,
        img: "/OIP (7).jpeg",
        name: "Arabica Coffee Body Scrub",
        price: 80.0,
        category: ["skin care"],
        sale: true,
    },
    {
        id: 24,
        img: "/serum.jpg",
        name: "Dior One Essential Skin Boosting Super Serum",
        price: 22.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 25,
        img: "/R (3).jpeg",
        name: "Versace Bright Crystal Perfume",
        price: 55.0,
        category: ["perfume"],
        sale: true,
    },
    {
        id: 26,
        img: "/7802985_1.webp",
        name: "Flormar Kiss Me More Lip Tattoo",
        price: 49.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 27,
        img: "/38985532Motivated__Matte_.jpg",
        name: "Motivated Matte Lipstick",
        price: 25.0,
        category: ["lipsticks", "makeup"],
        sale: true,
    },
    {
        id: 28,
        img: "/194251133690-1.webp",
        name: "Afterglow Sensual Shine Lipstick",
        price: 40.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 29,
        img: "/OIP (6).jpeg",
        name: "Gloss Pink with Collagen",
        price: 29.0,
        category: ["lipsticks"],
        sale: true,
    },
    {
        id: 30,
        img: "/OIP (5).jpeg",
        name: "Minerals Matte Lipstick",
        price: 43.0,
        category: ["lipsticks"],
        sale: false,
    },
    {
        id: 31,
        img: "/OIP (4).jpeg",
        name: "Natural Tea Body Wash",
        price: 38.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 32,
        img: "/OIP (3).jpeg",
        name: "Touch Keratosis Pilaris",
        price: 29.0,
        category: ["skin care"],
        sale: false,
    },
    {
        id: 33,
        img: "/OIP (2).jpeg",
        name: "Yves Saint Laurent Libre",
        price: 23.0,
        category: ["perfume"],
        sale: false,
    },
];